#line 2 "aic/aicasm.lex.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/ncvs/src/usr.bin/lex/skel.c,v 1.2 1996/12/14 05:48:48 steve Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 80
#define YY_END_OF_BUFFER 81
static yyconst short int yy_accept[256] =
    {   0,
        0,    0,    5,    5,    0,    0,    0,    0,   81,   79,
       14,    1,   66,   79,   66,   66,   77,   67,   69,   34,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,    5,
        4,    6,    7,   13,   12,   10,   11,   74,   80,   71,
       74,   72,   73,   14,    0,    0,    0,   77,   77,   77,
        2,   67,    0,   69,   78,   78,   78,   20,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   43,   45,   78,   78,   47,   78,   78,
       78,   78,   62,   78,   78,   78,   78,   78,   78,   78,

       78,    5,    6,    6,    8,    7,    3,    7,   13,    0,
       72,   72,   72,    0,    0,   68,   78,   78,   78,   51,
       50,   78,   78,   61,   23,   78,   78,   56,   41,   57,
       78,   54,   78,   78,    0,    9,   53,   42,   44,   46,
       48,   78,   40,   39,   78,   64,   58,   78,   63,   38,
       37,   27,   78,   35,   36,   78,   78,   55,   78,   59,
        0,    0,   78,   78,   78,   78,   78,   78,   78,   78,
       52,   49,   78,   78,   65,   24,   32,   78,   78,   78,
       26,   60,    0,    0,   78,   78,   78,   78,   78,   25,
       78,   78,   16,   78,   78,   78,   78,    0,    0,   78,

       78,   78,   78,   78,   78,   78,   78,   78,   78,   33,
       75,    0,   78,   78,   78,   78,   18,   30,   78,   78,
       78,   78,    0,   76,   70,   78,   78,   78,   78,   31,
       17,   15,   78,   76,   76,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   19,   29,   28,
       78,   22,   78,   21,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    1,    4,    1,    7,
        8,    9,    4,    4,   10,   11,   12,   13,   14,   14,
       14,   14,   14,   14,   14,   15,   15,    4,   16,    5,
        1,    5,    1,    1,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   24,   24,   26,   24,   27,   28,   24,
       24,   29,   24,   30,   24,   24,   31,   32,   24,   24,
        4,    1,    4,    1,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       48,   49,   24,   50,   51,   52,   53,   54,   55,   56,
       24,   57,    4,    4,    4,    4,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[58] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    3,    4,    5,
        5,    6,    5,    5,    5,    1,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5
    } ;

static yyconst short int yy_base[270] =
    {   0,
        0,    0,   55,   56,   63,   66,   74,   90,  229,  845,
      211,  845,  845,   47,   49,   51,   96,   98,  102,   76,
      107,   92,  109,  111,  113,  115,  121,  123,  126,  132,
      134,  144,  138,  136,  147,  164,  167,  176,  182,    0,
      845,  186,  187,    0,  845,  845,  845,  845,  845,  845,
      154,  193,  845,  198,  151,  138,  195,  199,  204,  206,
      845,  209,  220,  213,  232,  237,  241,  234,  239,  251,
      253,  255,  257,  259,  261,  265,  267,  270,  272,  274,
      279,  292,  285,  299,  301,  307,  311,  313,  315,  320,
      322,  324,  326,  329,  332,  340,  334,  342,  347,  349,

      351,    0,  293,  330,  845,  358,  845,  376,    0,  375,
      380,  382,  384,  144,  134,    0,  386,  391,  393,  395,
      397,  401,  403,  405,  407,  409,  411,  414,  416,  418,
      421,  425,  427,  429,  348,  845,  431,  433,  437,  441,
      443,  446,  450,  453,  457,  459,  464,  466,  468,  470,
      472,  474,  476,  480,  482,  485,  487,  489,  491,  493,
      119,  108,  500,  495,  504,  506,  508,  512,  517,  519,
      521,  523,  525,  527,  529,  533,  536,  538,  542,  547,
      549,  554,   93,   78,  557,  559,  562,  564,  567,  569,
      571,  575,  580,  584,  586,  588,  590,   91,   63,  592,

      594,  596,  603,  609,  611,  615,  619,  623,  625,  628,
      634,   34,  638,  640,  632,  643,  645,  647,  653,  657,
      660,  662,  668,  672,  845,  671,  673,  675,  677,  679,
      681,  688,  690,  698,  700,  700,  702,  704,  706,  708,
      713,  715,  722,  724,  732,  734,  736,  738,  740,  744,
      746,  753,  755,  757,  845,  781,  787,  793,  795,  797,
      799,  805,  810,  816,  822,  824,  826,  832,  838
    } ;

static yyconst short int yy_def[270] =
    {   0,
      255,    1,  256,  256,  257,  257,  258,  258,  255,  255,
      255,  255,  255,  255,  259,  260,  260,  259,  259,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  262,
      255,  263,  264,  265,  255,  255,  255,  255,  255,  255,
      266,  267,  255,  255,  255,  255,  259,  260,  260,  260,
      255,  259,  259,  259,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,

      261,  262,  263,  263,  255,  264,  255,  264,  265,  266,
      267,  267,  267,  255,  255,   63,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  255,  255,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      255,  255,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  255,  255,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  255,  255,  261,

      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      268,  255,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  268,  269,  255,  261,  261,  261,  261,  261,
      261,  261,  261,  269,  269,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,    0,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255
    } ;

static yyconst short int yy_nxt[903] =
    {   0,
       10,   11,   12,   13,   13,   14,   13,   13,   10,   15,
       16,   17,   18,   19,   19,   13,   20,   21,   22,   22,
       23,   22,   22,   22,   22,   22,   22,   22,   24,   22,
       25,   22,   22,   26,   27,   28,   29,   30,   22,   22,
       22,   31,   32,   22,   22,   33,   34,   35,   22,   36,
       37,   38,   22,   22,   22,   39,   22,   41,   41,   58,
       58,   60,   60,   42,   42,   45,   43,   43,   45,   46,
       47,  225,   46,   47,   48,   48,   49,   48,   50,   48,
       48,   48,   48,   55,   52,   52,   58,   58,   56,   53,
       48,   48,   49,   48,   50,   48,   48,   48,   48,  212,

       52,   52,   58,   58,   61,   53,   60,   60,   58,   58,
       62,   62,   58,   58,   64,   64,   64,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   66,  211,   63,
      199,   58,   58,   58,   58,   67,   58,   58,   68,  198,
       68,   68,   58,   58,   58,   58,   58,   58,   58,   58,
       69,   70,  184,   63,   58,   58,   75,   58,   58,   71,
      183,   72,   73,   79,  111,  111,   74,   76,   77,  162,
       78,   89,   82,   80,   58,   58,   81,   58,   58,   84,
       83,   85,  161,   92,  115,   90,   58,   58,  114,   86,
       87,   91,   58,   58,  104,  107,   93,  105,  108,   54,

       88,   94,   96,  113,  113,   58,   58,   97,   98,   60,
       60,   95,   54,  100,   60,   60,   60,   60,   99,   58,
       58,   62,   62,   58,   58,   64,   64,   64,  255,  101,
       58,   58,  116,  116,  116,  255,  116,  116,  116,  116,
      116,  116,   58,   58,   58,   58,  255,   58,   58,   58,
       58,   58,   58,  116,  116,  116,  116,  116,  116,  117,
      118,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,  255,  119,   58,   58,   58,   58,  255,
       58,   58,   58,   58,   58,   58,  120,  121,  255,   58,
       58,  124,  255,  135,  122,   58,   58,  123,  136,  255,

      128,  255,   58,   58,  255,  127,  126,  132,  125,   58,
       58,   58,   58,  255,  129,  130,  131,   58,   58,  255,
      137,   58,   58,   58,   58,   58,   58,  255,  133,  134,
       58,   58,   58,   58,   58,   58,   58,   58,  104,   58,
       58,  105,   58,   58,   58,   58,  139,  255,  140,  135,
       58,   58,   58,   58,  136,  138,  255,   58,   58,   58,
       58,   58,   58,  144,  255,  142,  255,  141,  148,  255,
      145,  255,  146,  143,  152,  147,  150,  255,  154,  255,
      149,  151,  158,  155,  255,  111,  111,  108,  156,  153,
      113,  113,  113,  113,  113,  113,   58,   58,  157,  159,

      160,   58,   58,   58,   58,   58,   58,   58,   58,  255,
      163,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,  164,   58,   58,   58,   58,   58,   58,
      165,   58,   58,  255,  168,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,  166,  167,   58,   58,  255,
      169,   58,   58,   58,   58,  172,   58,   58,  255,  170,
       58,   58,  171,   58,   58,  255,  175,   58,   58,   58,
       58,  173,  255,  174,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,  255,  176,
       58,   58,   58,   58,  177,   58,   58,   58,   58,   58,

       58,   58,   58,   58,   58,   58,   58,  178,  255,  179,
       58,   58,  255,  186,   58,   58,   58,   58,   58,   58,
      255,  180,   58,   58,  181,  255,  185,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,  255,  182,   58,   58,  189,   58,   58,   58,   58,
      255,  188,   58,   58,  187,  255,  192,   58,   58,   58,
       58,  255,  190,  191,   58,   58,  255,   58,   58,   58,
       58,  194,   58,   58,   58,   58,  193,   58,   58,   58,
       58,   58,   58,  255,  197,   58,   58,  201,  195,  200,
       58,   58,  255,  196,   58,   58,   58,   58,   58,   58,

       58,   58,   58,   58,   58,   58,   58,   58,  205,  255,
      213,  255,  202,   58,   58,  255,  203,  204,  214,   58,
       58,   58,   58,  209,  206,   58,   58,  255,  215,   58,
       58,  207,  255,   58,   58,   58,   58,  208,   58,   58,
      224,  224,   58,   58,  255,  210,  255,  216,   58,   58,
       58,   58,  220,   58,   58,   58,   58,   58,   58,  217,
      221,  218,  219,   58,   58,  222,  226,   58,   58,  227,
       58,   58,   58,   58,  224,  224,  229,  228,  235,  235,
      255,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,  231,  233,  236,  255,  237,   58,   58,

       58,   58,  255,  230,  235,  235,  235,  235,  255,  232,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
      242,  255,  238,   58,   58,   58,   58,  255,  239,  241,
      255,  247,   58,   58,   58,   58,  255,  246,  255,  240,
      243,  245,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,  251,  244,   58,   58,   58,   58,  255,  248,
      255,  252,  253,   58,   58,   58,   58,   58,   58,  255,
      255,  255,  255,  249,  255,  255,  255,  250,  255,  255,
      254,   40,   40,   40,   40,   40,   40,   44,   44,   44,
       44,   44,   44,   51,   51,   51,   51,   51,   51,   57,

       57,   59,   59,   65,   65,  102,  255,  102,  255,  102,
      103,  255,  103,  103,  103,  103,  106,  255,  106,  106,
      106,  106,  109,  255,  255,  109,  109,  109,  110,  110,
      112,  112,  223,  255,  223,  223,  223,  223,  234,  255,
      234,  234,  234,  234,    9,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,

      255,  255
    } ;

static yyconst short int yy_chk[903] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,   15,
       15,   16,   16,    3,    4,    5,    3,    4,    6,    5,
        5,  212,    6,    6,    7,    7,    7,    7,    7,    7,
        7,    7,    7,   14,    7,    7,   20,   20,   14,    7,
        8,    8,    8,    8,    8,    8,    8,    8,    8,  199,

        8,    8,   22,   22,   17,    8,   17,   17,   18,   18,
       18,   18,   19,   19,   19,   19,   19,   21,   21,   23,
       23,   24,   24,   25,   25,   26,   26,   21,  198,   18,
      184,   27,   27,   28,   28,   23,   29,   29,   24,  183,
       25,   24,   30,   30,   31,   31,   34,   34,   33,   33,
       26,   26,  162,   18,   32,   32,   28,   35,   35,   26,
      161,   26,   27,   29,   51,   51,   27,   28,   28,  115,
       28,   33,   31,   29,   36,   36,   30,   37,   37,   32,
       31,   32,  114,   34,   56,   33,   38,   38,   55,   32,
       32,   33,   39,   39,   42,   43,   35,   42,   43,   54,

       32,   36,   37,   52,   52,   57,   57,   37,   37,   58,
       58,   36,   11,   38,   59,   59,   60,   60,   37,   62,
       62,   62,   62,   64,   64,   64,   64,   64,    9,   39,
       63,   63,   63,   63,   63,    0,   63,   63,   63,   63,
       63,   63,   65,   65,   68,   68,    0,   66,   66,   69,
       69,   67,   67,   63,   63,   63,   63,   63,   63,   66,
       67,   70,   70,   71,   71,   72,   72,   73,   73,   74,
       74,   75,   75,    0,   69,   76,   76,   77,   77,    0,
       78,   78,   79,   79,   80,   80,   70,   70,    0,   81,
       81,   72,    0,   82,   71,   83,   83,   71,   82,    0,

       76,  103,   82,   82,  103,   75,   74,   79,   73,   84,
       84,   85,   85,    0,   76,   77,   78,   86,   86,    0,
       83,   87,   87,   88,   88,   89,   89,    0,   80,   81,
       90,   90,   91,   91,   92,   92,   93,   93,  104,   94,
       94,  104,   95,   95,   97,   97,   87,    0,   87,  135,
       96,   96,   98,   98,  135,   86,    0,   99,   99,  100,
      100,  101,  101,   91,    0,   89,  106,   87,   94,  106,
       92,    0,   92,   90,   96,   92,   95,    0,   97,    0,
       94,   95,   99,   97,  108,  110,  110,  108,   98,   96,
      111,  111,  112,  112,  113,  113,  117,  117,   98,  100,

      101,  118,  118,  119,  119,  120,  120,  121,  121,    0,
      117,  122,  122,  123,  123,  124,  124,  125,  125,  126,
      126,  127,  127,  118,  128,  128,  129,  129,  130,  130,
      119,  131,  131,    0,  122,  132,  132,  133,  133,  134,
      134,  137,  137,  138,  138,  119,  121,  139,  139,    0,
      123,  140,  140,  141,  141,  127,  142,  142,    0,  123,
      143,  143,  126,  144,  144,    0,  134,  145,  145,  146,
      146,  131,    0,  133,  147,  147,  148,  148,  149,  149,
      150,  150,  151,  151,  152,  152,  153,  153,    0,  142,
      154,  154,  155,  155,  145,  156,  156,  157,  157,  158,

      158,  159,  159,  160,  160,  164,  164,  148,    0,  153,
      163,  163,    0,  164,  165,  165,  166,  166,  167,  167,
        0,  156,  168,  168,  157,    0,  163,  169,  169,  170,
      170,  171,  171,  172,  172,  173,  173,  174,  174,  175,
      175,    0,  159,  176,  176,  167,  177,  177,  178,  178,
        0,  166,  179,  179,  165,    0,  170,  180,  180,  181,
      181,    0,  168,  169,  182,  182,    0,  185,  185,  186,
      186,  174,  187,  187,  188,  188,  173,  189,  189,  190,
      190,  191,  191,    0,  180,  192,  192,  186,  178,  185,
      193,  193,    0,  179,  194,  194,  195,  195,  196,  196,

      197,  197,  200,  200,  201,  201,  202,  202,  191,    0,
      200,    0,  187,  203,  203,    0,  188,  189,  201,  204,
      204,  205,  205,  196,  192,  206,  206,    0,  202,  207,
      207,  194,    0,  208,  208,  209,  209,  195,  210,  210,
      211,  211,  215,  215,    0,  197,    0,  203,  213,  213,
      214,  214,  207,  216,  216,  217,  217,  218,  218,  204,
      208,  205,  206,  219,  219,  209,  213,  220,  220,  214,
      221,  221,  222,  222,  223,  223,  216,  215,  224,  224,
        0,  226,  226,  227,  227,  228,  228,  229,  229,  230,
      230,  231,  231,  220,  222,  226,    0,  227,  232,  232,

      233,  233,    0,  219,  234,  234,  235,  235,    0,  221,
      236,  236,  237,  237,  238,  238,  239,  239,  240,  240,
      237,    0,  228,  241,  241,  242,  242,    0,  229,  236,
        0,  242,  243,  243,  244,  244,    0,  241,    0,  233,
      238,  240,  245,  245,  246,  246,  247,  247,  248,  248,
      249,  249,  246,  239,  250,  250,  251,  251,    0,  243,
        0,  247,  251,  252,  252,  253,  253,  254,  254,    0,
        0,    0,    0,  244,    0,    0,    0,  245,    0,    0,
      253,  256,  256,  256,  256,  256,  256,  257,  257,  257,
      257,  257,  257,  258,  258,  258,  258,  258,  258,  259,

      259,  260,  260,  261,  261,  262,    0,  262,    0,  262,
      263,    0,  263,  263,  263,  263,  264,    0,  264,  264,
      264,  264,  265,    0,    0,  265,  265,  265,  266,  266,
      267,  267,  268,    0,  268,  268,  268,  268,  269,    0,
      269,  269,  269,  269,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,

      255,  255
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "aic/aicasm.l.v"
#define INITIAL 0
#line 2 "aic/aicasm.l.v"
/*
 ****************************************************************
 *								*
 *			asm.2940.l				*
 *								*
 *	Montador para a linguagem simbólica da placa 2940	*
 *								*
 *	Versão	4.0.0, de 08.03.01				*
 *		4.0.0, de 08.03.01				*
 *								*
 *	Módulo: Núcleo						*
 *		NÚCLEO do TROPIX para PC			*
 *								*
 *	TROPIX: Sistema Operacional Tempo-Real Multiprocessado	*
 *		Copyright © 2000 NCE/UFRJ - tecle "man licença"	*
 *								*
 ****************************************************************
 */

#include "../h/types.h"
#include "../h/queue.h"

#include <stdio.h>
#include <string.h>

#include "../aic/sysexits.h"
#include "../aic/aicasm.h"
#include "../aic/asm_symbol.h"
#include "../aic/aicasm.tab.h"

/*
 ****************************************************************
 *	Definições globais					*
 ****************************************************************
 */
#define MAX_STR_CONST 256
#define	PATH_MAX	1024		/* PROVISÓRIO */

char	string_buf[MAX_STR_CONST];
char	*string_buf_ptr;
int	parren_count;

#define	YY_NO_SCAN_STRING
#define	YY_NO_SCAN_BYTES
#define	YY_NO_SCAN_BUFFER

/*
 ******	Protótipos de funções ***********************************
 */
symbol_t *symtable_get (const char *name);

#define COMMENT 1

#define CEXPR 2

#define INCLUDE 3

#line 708 "aic/aicasm.lex.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 63 "aic/aicasm.l.v"

#line 861 "aic/aicasm.lex.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 256 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 845 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 64 "aic/aicasm.l.v"
{ ++yylineno; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 65 "aic/aicasm.l.v"
{ BEGIN COMMENT;  /* Enter comment eating state */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 66 "aic/aicasm.l.v"
{ fprintf(stderr, "Warning! Comment within comment."); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 67 "aic/aicasm.l.v"
{ ++yylineno; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 68 "aic/aicasm.l.v"
;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 69 "aic/aicasm.l.v"
;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 70 "aic/aicasm.l.v"
;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 71 "aic/aicasm.l.v"
{ BEGIN INITIAL; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 72 "aic/aicasm.l.v"
{
				string_buf_ptr = string_buf;
				parren_count = 1;
				BEGIN CEXPR;
				return T_IF;
			}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 78 "aic/aicasm.l.v"
{	*string_buf_ptr++ = '('; parren_count++; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 79 "aic/aicasm.l.v"
{
				parren_count--;
				if (parren_count == 0) {
					/* All done */
					BEGIN INITIAL;
					*string_buf_ptr = '\0';
					yylval.sym = symtable_get(string_buf);
					return T_CEXPR;
				} else {
					*string_buf_ptr++ = ')';
				}
			}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 91 "aic/aicasm.l.v"
{ ++yylineno; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 92 "aic/aicasm.l.v"
{
				char *yptr = yytext;

				while (*yptr != '\0') {
					/* Remove duplicate spaces */
					if (*yptr == '\t')
						*yptr = ' ';
					if (*yptr == ' '
					 && string_buf_ptr != string_buf
					 && string_buf_ptr[-1] == ' ')
						yptr++;
					else 
						*string_buf_ptr++ = *yptr++;
				}
			}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 108 "aic/aicasm.l.v"
;
	YY_BREAK
/* Register/SCB/SRAM definition keywords */
case 15:
YY_RULE_SETUP
#line 111 "aic/aicasm.l.v"
{ return T_REGISTER; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 112 "aic/aicasm.l.v"
{ yylval.value = FALSE; return T_CONST; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 113 "aic/aicasm.l.v"
{ return T_DOWNLOAD; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 114 "aic/aicasm.l.v"
{ return T_ADDRESS; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 115 "aic/aicasm.l.v"
{ return T_ACCESS_MODE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 116 "aic/aicasm.l.v"
{
				 if (strcmp(yytext, "RW") == 0)
					yylval.value = RW;
				 else if (strcmp(yytext, "RO") == 0)
					yylval.value = RO;
				 else
					yylval.value = WO;
				 return T_MODE;
			}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 125 "aic/aicasm.l.v"
{ return T_BEGIN_CS; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 126 "aic/aicasm.l.v"
{ return T_END_CS; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 127 "aic/aicasm.l.v"
{ return T_BIT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 128 "aic/aicasm.l.v"
{ return T_MASK; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 129 "aic/aicasm.l.v"
{ return T_ALIAS; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 130 "aic/aicasm.l.v"
{ return T_SIZE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 131 "aic/aicasm.l.v"
{ return T_SCB; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 132 "aic/aicasm.l.v"
{ return T_SRAM; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 133 "aic/aicasm.l.v"
{ return T_ACCUM; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 134 "aic/aicasm.l.v"
{ return T_ALLONES; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 135 "aic/aicasm.l.v"
{ return T_ALLZEROS; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 136 "aic/aicasm.l.v"
{ return T_NONE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 137 "aic/aicasm.l.v"
{ return T_SINDEX; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 138 "aic/aicasm.l.v"
{ return T_A; }
	YY_BREAK
/* Opcodes */
case 35:
YY_RULE_SETUP
#line 141 "aic/aicasm.l.v"
{ return T_SHL; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 142 "aic/aicasm.l.v"
{ return T_SHR; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 143 "aic/aicasm.l.v"
{ return T_ROR; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 144 "aic/aicasm.l.v"
{ return T_ROL; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 145 "aic/aicasm.l.v"
{ return T_MVI; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 146 "aic/aicasm.l.v"
{ return T_MOV; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 147 "aic/aicasm.l.v"
{ return T_CLR; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 148 "aic/aicasm.l.v"
{ return T_JMP; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 149 "aic/aicasm.l.v"
{ return T_JC;	}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 150 "aic/aicasm.l.v"
{ return T_JNC;	}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 151 "aic/aicasm.l.v"
{ return T_JE;	}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 152 "aic/aicasm.l.v"
{ return T_JNE;	}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 153 "aic/aicasm.l.v"
{ return T_JZ;	}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 154 "aic/aicasm.l.v"
{ return T_JNZ;	}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 155 "aic/aicasm.l.v"
{ return T_CALL; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 156 "aic/aicasm.l.v"
{ return T_ADD; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 157 "aic/aicasm.l.v"
{ return T_ADC; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 158 "aic/aicasm.l.v"
{ return T_BMOV; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 159 "aic/aicasm.l.v"
{ return T_INC; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 160 "aic/aicasm.l.v"
{ return T_DEC; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 161 "aic/aicasm.l.v"
{ return T_STC;	}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 162 "aic/aicasm.l.v"
{ return T_CLC; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 163 "aic/aicasm.l.v"
{ return T_CMP;	}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 164 "aic/aicasm.l.v"
{ return T_NOT;	}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 165 "aic/aicasm.l.v"
{ return T_XOR;	}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 166 "aic/aicasm.l.v"
{ return T_TEST;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 167 "aic/aicasm.l.v"
{ return T_AND;	}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 168 "aic/aicasm.l.v"
{ return T_OR;	}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 169 "aic/aicasm.l.v"
{ return T_RET; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 170 "aic/aicasm.l.v"
{ return T_NOP; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 171 "aic/aicasm.l.v"
{ return T_ELSE; }
	YY_BREAK
/* Allowed Symbols */
case 66:
YY_RULE_SETUP
#line 174 "aic/aicasm.l.v"
{ return yytext[0]; }
	YY_BREAK
/* Number processing */
case 67:
YY_RULE_SETUP
#line 177 "aic/aicasm.l.v"
{
				yylval.value = strtol(yytext, NULL, 8);
				return T_NUMBER;
			}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 182 "aic/aicasm.l.v"
{
				yylval.value = strtoul(yytext + 2, NULL, 16);
				return T_NUMBER;
			}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 187 "aic/aicasm.l.v"
{
				yylval.value = strtol(yytext, NULL, 10);
				return T_NUMBER;
			}
	YY_BREAK
/* Include Files */
case 70:
YY_RULE_SETUP
#line 193 "aic/aicasm.l.v"
{ return T_INCLUDE; BEGIN INCLUDE;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 194 "aic/aicasm.l.v"
{ return yytext[0]; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 195 "aic/aicasm.l.v"
{ yylval.str = strdup(yytext); return T_PATH; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 196 "aic/aicasm.l.v"
{ BEGIN INITIAL; return yytext[0]; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 197 "aic/aicasm.l.v"
{ stop("Invalid include line", EX_DATAERR); }
	YY_BREAK
/* For parsing C include files with #define foo */
case 75:
YY_RULE_SETUP
#line 200 "aic/aicasm.l.v"
{ yylval.value = TRUE; return T_CONST; }
	YY_BREAK
/* Throw away macros */
case 76:
YY_RULE_SETUP
#line 202 "aic/aicasm.l.v"
;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 203 "aic/aicasm.l.v"
{ yylval.str = strdup(yytext); return T_PATH; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 205 "aic/aicasm.l.v"
{ yylval.sym = symtable_get(yytext);  return T_SYMBOL; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 207 "aic/aicasm.l.v"
{ 
				char buf[255];

				snprintf(buf, sizeof(buf), "Invalid character "
					 "'%c'", yytext[0]);
				stop(buf, EX_DATAERR);
			}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 214 "aic/aicasm.l.v"
ECHO;
	YY_BREAK
#line 1404 "aic/aicasm.lex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(CEXPR):
case YY_STATE_EOF(INCLUDE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 256 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 256 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 255);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 214 "aic/aicasm.l.v"


typedef struct include
{
        YY_BUFFER_STATE  buffer;
        int              lineno;
        const char       *filename;
	SLIST_ENTRY(include) links;

}	include_t;

SLIST_HEAD(, include) include_stack;

void
include_file (const char *file_name, include_type type)
{
	FILE *newfile;
	include_t *include;

	newfile = NULL;
	/* Try the current directory first */
	if (includes_search_curdir != 0 || type == SOURCE_FILE)
		newfile = fopen(file_name, "r");

	if (newfile == NULL && type != SOURCE_FILE) {
                path_entry_t include_dir;
                for (include_dir = search_path.slh_first;
                     include_dir != NULL;                
                     include_dir = include_dir->links.sle_next) {
			char fullname[PATH_MAX];

			if ((include_dir->quoted_includes_only == TRUE)
			 && (type != QUOTED_INCLUDE))
				continue;

			snprintf(fullname, sizeof(fullname),
				 "%s/%s", include_dir->directory, file_name);

			if ((newfile = fopen(fullname, "r")) != NULL)
				break;
                }
        }

	if (newfile == NULL) {
		perror(file_name);
		stop("Unable to open input file", EX_SOFTWARE);
		/* NOTREACHED */
	}

	if (type != SOURCE_FILE) {
		include = (include_t *)malloc(sizeof(include_t));
		if (include == NULL) {
			stop("Unable to allocate include stack entry",
			     EX_SOFTWARE);
			/* NOTREACHED */
		}
		include->buffer = YY_CURRENT_BUFFER;
		include->lineno = yylineno;
		include->filename = yyfilename;
		SLIST_INSERT_HEAD(&include_stack, include, links);
	}
	yy_switch_to_buffer(yy_create_buffer(newfile, YY_BUF_SIZE));
	yylineno = 1;
	yyfilename = strdup(file_name);
}

int
yywrap (void)
{
	include_t *include;

	yy_delete_buffer(YY_CURRENT_BUFFER);
	(void)fclose(yyin);
	if (yyfilename != NULL)
		free ((char *)yyfilename);
	yyfilename = NULL;
	include = include_stack.slh_first;
	if (include != NULL) {
		yy_switch_to_buffer(include->buffer);
		yylineno = include->lineno;
		yyfilename = include->filename;
		SLIST_REMOVE_HEAD(&include_stack, links);
		free(include);
		return (0);
	}
	return (1);
}
